### ISSUE TITLE
Couldn't find any clusters on your configuration file

### ISSUE THREAD

**Issue by GusPr** [tchiotludo/kafkahq#106]
Hi! 
I'm testing with a confluent cluster with name "test".

My config looks like this but it says no cluster is found. Could anyone take a look at the config? Thanks

```
  connections:
    test: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "xyz.aws.confluent.cloud:9092"
      schema-registry:
        url: "abc.aws.confluent.cloud" # schema registry url (optional)
        basic-auth: # Basic Auth user / pass
          username: schema-registry-api-key
          password: schema-registry-api-secret
```

**Comment by tchiotludo** [comment]
Hi, 
your configuration look fine. 
Do you have the `kafkahq:` base on your yaml, like : 
```
kafkahq:
  connections:
    test: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "xyz.aws.confluent.cloud:9092"
      schema-registry:
        url: "abc.aws.confluent.cloud" # schema registry url (optional)
        basic-auth: # Basic Auth user / pass
          username: schema-registry-api-key
          password: schema-registry-api-secret
```
?

**Comment by GusPr** [comment]
Hi! Yes I have. The rest of the config is as same as the example.

**Comment by tchiotludo** [comment]
Ok 

- Can you send the full output of the logs ? 
- What kind of installation you use (jar / docker) ?

**Comment by GusPr** [comment]
here's the log, https://gist.github.com/GusPr/3b217a827b8eadf33f85e7fc660c029c
I use the latest jar.

**Comment by tchiotludo** [comment]
Do you try with absolute path ? 
I'm not really aware of windows but I think the path must be absolute

**Comment by GusPr** [comment]
With absolute path, I get nullPointerException, https://gist.github.com/GusPr/41ab2dd1fe608d73184e8c1cccd64adb

**Comment by tchiotludo** [comment]
your url is weird: `/docker-kafka-server/topic`.
Since your config is `test` (friendly name) the url must be `/test/topic`

**Comment by GusPr** [comment]
my `localhost:8080` got redirected to there automatically. When visiting `/test/topic`, the browser hangs and no new logs

**Comment by GusPr** [comment]
It stopped after my last comment, `org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
`

**Comment by tchiotludo** [comment]
Ok seems better now. 
For the redirection, It was save in cache by your browser (you must have try with config name docker-kafka-server). 
For the timeout, seems that you don't have direct access to cluster from your computer.
Try to see if port if open.

**Comment by GusPr** [comment]
> For the redirection, It was save in cache by your browser (you must have try with config name docker-kafka-server).
That's correct, I did

> For the timeout, seems that you don't have direct access to cluster from your computer.
Try to see if port if open.
The cluster is up running on confluent cloud.

**Comment by tchiotludo** [comment]
I'm talking reachable from your local desktop.
A timeout mean that the port is not open ( maybe network restrictions from confluent cloud or your local network)

**Comment by yuhe-mercell** [comment]
Yes, I could produce data and they show up in confluent cloud.

**Comment by GusPr** [comment]
Hello, sorry for a late reply.

Yes, I could produce some data locally and they show up in confluent cloud.

**Comment by tchiotludo** [comment]
Just try with confluent cloud, and it work with on dev env since last bug fix  (https://github.com/tchiotludo/kafkahq/issues/111)

Just add this configuration : 
```yaml
kafkahq:
  connections:
    {{url-friendly-name}}:
      properties:
        bootstrap.servers: "{{host}}.gcp.confluent.cloud:9092"
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="{{host}}" password="{{password}}";
```

Does this works now for you ?

**Comment by GusPr** [comment]
Tried

```
kafkahq:
  connections:
    test: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "xyz.aws.confluent.cloud:9092"
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="API-key" password="API-secret";
      schema-registry:
        url: "abc.aws.confluent.cloud" # schema registry url (optional)
        basic-auth: # Basic Auth user / pass
          username: schema-registry-api-key
          password: schema-registry-api-secret
```

https://gist.github.com/GusPr/62644f456b063f9fdcd64a9a6925ed95
