### ISSUE TITLE
Login fails everytime

### ISSUE THREAD

**Issue by druzmieres** [tchiotludo/kafkahq#117]
I have this configuration in my `application.yml`.
```
# Auth & Roles (optional)
  security:
    default-roles: # Roles available for all the user even unlogged user
      - topic/read
      - node/read
      - topic/data/read
      - group/read
      - registry/read
      - connect/read

    # Basic auth configuration
    basic-auth:
      admin:
        password: 03AC674216F3E15C761EE1A5E255F067953623C8B388B4459E13F978D7C846F4
        roles: # Role for current users
          - topic/read
          - group/read
          - group/delete
          - topic/insert
          - topic/delete
          - topic/config/update
          - node/read
          - node/config/update
          - topic/data/read
          - topic/data/insert
          - topic/data/delete
          - group/offsets/update
          - registry/read
          - registry/insert
          - registry/update
          - registry/delete
          - registry/version/delete
          - connect/read
          - connect/insert
          - connect/update
          - connect/delete
          - connect/state/update
```

I generated the sha256 with the string 1234. Nevertheless, when I try to login using 1234 as the password the login fails. I also tried using the sha256 as the password, but that doesn't work either.
