### ISSUE TITLE
Connect Multicluster

### ISSUE THREAD

**Issue by alpeza** [tchiotludo/kafkahq#127]
Hello

We are going to make that the KafkaHQ can interact with multiple Connect clusters. We would like make a pull request later. Did you think of any concrete way to do this and we would stick to this pattern?

Regards

**Comment by tchiotludo** [comment]
Just to be sure to understand ?
You want to allow multiple connect cluster for 1 Kafka cluster ?

**Comment by alpeza** [comment]
exact.
and thanks for the reply

**Comment by alpeza** [comment]
Hi this is what we need:

![](https://i.pinimg.com/originals/78/5d/de/785dde837f45bdb3d0f693cef43c7866.png)


We have thought two approaches for implement this:

### First Approach


We put in the `application.yml` file the urls of the different connect clusters.

![](https://i.pinimg.com/originals/cd/dc/41/cddc4116186676414fa02a09c1065684.png)

### Second Approach

Another approach is that KafkaHQ discovers the Connects that are added to the Kafka Broker.
This can be do by capturing the topics that Connect generates internally.


![](https://i.pinimg.com/originals/70/23/25/702325d18543b76be80b1958a1edf554.png)


We would like to add one or another of these solutions to the main version of HQ. Would you let us implement any of these solutions to add to the master version

thanks

**Comment by tchiotludo** [comment]
Hello, 

Thanks for your detail review 👍

I'll vote for first version. I think it will work that all the use case (for example, dedicated cluster for storing offsets). 
The second one is a little big more tricky, and maybe not work if there is an authentication on connect cluster (that is the case for most saas Kafka provider)

For the list of connect cluster list, I prefer to have the list of cluster on the left menu (like the Kafka cluster), and to have different route for the different connect endpoint, so configuration of connect must have a name (not a simple array in your example)

Let me know if it's ok for you or you need more precision

And thanks to improve KafkaHQ 👍

**Comment by alpeza** [comment]
Hi tchiotludo

Functionally I understand something like this:


* `Application.yml`:

```yaml
  connect-clusters:
    MyConnectCluster1:
      url: "http://thednsofmyconnectcluster:8083"
      basic-auth-username: "connect basic auth username"
      basic-auth-password: "connect basic auth password"
      ssl-trust-store: "/app/truststore.jks"
      ssl-trust-store-password: "trust-store-password"
      ssl-key-store: "/app/truststore.jks"
      ssl-key-store-password: "key-store-password"
    YetAnotherConnect:
      url: "http://thednsofyetanother:8083"
    AndAnotherConnect:
      url: "http://localhost:8083"
```

* Frontend:

![](https://i.pinimg.com/originals/b6/d3/a4/b6d3a49b6e43b737c50b7e1eb80bfe24.png)


it is right?

thanks 
regards
