### ISSUE TITLE
Something wrong with my config file?

### ISSUE THREAD

**Issue by jessetandor** [tchiotludo/kafkahq#141]
I'm trying to run with this config file - its the bare minimum from what i can see. The broker has sasl configured and its running on a remote machine ( URL specified in bootstrap ). Did I miss anything?

```
kafkahq:
  connections:
    Dev-multi-kafka-test:
      properties:
        bootstrap.servers: "kafka-mdb1.dev-tll.workshop.works:9092"
            security.protocol: SASL_SSL
            sasl.mechanism: SCRAM-SHA-256
            sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="admin_pass" password="123";
            ssl.truststore.location: /app/truststore.jks
            ssl.truststore.password: password
            ssl.keystore.location: /app/keystore.jks
            ssl.keystore.password: password
            ssl.key.password: password
```

**Comment by tchiotludo** [comment]
Hard to say like that.

What is your env (runtime docker or jar with java version) ? 
What does the log output ? 
What is the error on brower ? 
... 

The only things is see is uppercase on `Dev-multi-kafka-test` that if not tested by myself, always lowercase.

**Comment by jessetandor** [comment]
I'm running docker locally on my machine. I just get output from the command 
`docker run -d  -p 8080:8080 -v /Users/jesse/Desktop/application.yml:/app/application.yml tchiotludo/kafkahq` which is `89e321e7e30d37c0311235ec1a9a64a361a74e51f86b7b8e1a54036ea1fe21cc`

And checking the logs from docker - `docker logs 89e321e7e30d37c0311235ec1a9a64a361a74e51f86b7b8e1a54036ea1fe21cc`

```
2019-11-07 14:06:34,952 ERROR main       i.m.runtime.Micronaut      Error starting Micronaut server: while parsing a block mapping
 in 'reader', line 5, column 9:
            bootstrap.servers: "kafka-mdb1.d ...
            ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 6, column 11:
              security.protocol: SASL_SSL
              ^

org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 5, column 9:
            bootstrap.servers: "kafka-mdb1.d ...
            ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 6, column 11:
              security.protocol: SASL_SSL
```

It looks like my syntax is incorrect somehow...

**Comment by tchiotludo** [comment]
yes seems to be in the yaml matrix, maybe to space failed : try here your yaml : http://www.yamllint.com/

**Comment by jessetandor** [comment]
bootstrap.servers: "kafka-mdb1.dev-tll.workshop.works:9092"
            security.protocol: SASL_SSL

Was the problem. It should be 

        bootstrap.servers: "kafka-mdb1.dev-tll.workshop.works:9092"
        security.protocol: SASL_SSL

**Comment by tchiotludo** [comment]
:+1: closing if it work :)

**Comment by jessetandor** [comment]
I still can't connect to the broker though :

{"message":"Internal Server Error: Couldn't find any clusters on your configuration file, please ensure that the configuration file is loaded correctly","logref":{"present":false},"path":{"present":false}}

The config file is correct - no errors:

_---
kafkahq:
  connections:
    dev:
      properties:
        bootstrap.servers: "kafka-mdb1.dev-tll.workshop.works:9092"
        sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"cluster_admin\" password=\"123\";"
        sasl.mechanism: SCRAM-SHA-256
        security.protocol: SASL_SSL_

kafka-mdb1.dev-tll.workshop.works is the machine hostname - I've also tried to use the general cluster name from consul itself ( kafka-microservices-db.service.consul:9092 ). And then also the IP address of the kafka-mdb1 machine... None have connected.

Im mainly using the java method - 'java -Dmicronaut.config.files=application.yml -jar kafkahq.jar'. Both files in the same directory.

Anything else i can try?

**Comment by tchiotludo** [comment]
mostly must be a indentation problem ! 
This error was throw by KafkaHQ to expose that the file is incorrect.

Can you attach the raw files please ? or here is the correct version : 

```yaml
kafkahq:
  connections:
    dev:
      properties:
        bootstrap.servers: "kafka-mdb1.dev-tll.workshop.works:9092"
        sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username="cluster_admin" password="123";"
        sasl.mechanism: SCRAM-SHA-256
        security.protocol: SASL_SSL
```

**Comment by jessetandor** [comment]
That fails...Tit complains that the syntax is incorrect without \ for username and password.

kafkahq:
  connections:
    dev:
      properties:
        bootstrap.servers: "kafka-microservices-db.service.consul:9092"
        sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"cluster_admin\" password=\"123\";"
        sasl.mechanism: SCRAM-SHA-256
        security.protocol: SASL_SSLL

**Comment by tchiotludo** [comment]
ok I see the " failed.
try with this : 

```yaml 
kafkahq:
  connections:
    dev:
      properties:
        bootstrap.servers: "kafka-mdb1.dev-tll.workshop.works:9092"
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="cluster_admin" password="123";
        sasl.mechanism: SCRAM-SHA-256
        security.protocol: SASL_SSL
```
