### ISSUE TITLE
handling of session expiration

### ISSUE THREAD

**Issue by jorgheymans** [tchiotludo/kafkahq#157]
When for example live-tailing a topic and the session expires, no messages will be received anymore if roles are required to read the topic. From a UI perspective unless you pay attention to the bottom right corner it can be confusing. When the session expires i think that upon next click or refresh you should be redirected to the login page again. User experience wise, by default it's probably better to have a default session timeout of a couple of hours. 

There may be a micronaut setting for this? https://docs.micronaut.io/latest/guide/configurationreference.html

**Comment by tchiotludo** [comment]
Thanks for the report. 

Just some question to help to understand :  

- What was your configuration (seems to be authenticated with basic auth) ? 
- How many time before the session time out ?

**Comment by jorgheymans** [comment]
indeed, basic auth is configured. I did not set any specific timeout so guessing defaults apply.

security wise the config looks like this:

```yaml
  # Auth & Roles (optional)
  security:
    #default-roles: # Roles available for all the user even unlogged user

    # Basic auth configuration
    basic-auth:
      user1:
        password: "c10688a28517e1550645c69fdf13e7ab6b74ed87094bbe01f28e886490b7023e"
        roles: # Role for current users
          - topic/read
          - node/read
          - topic/data/read
          - group/read
          - acls/read
        attributes:
          # Regexp to filter topic available for current user
          topics-filter-regexp: "test.*"
```

With this configuration, my goal was to actually deny users that are not logged on access to the system, but that does not seem to work. It seems that, even though the user is not logged on, topic data for example can still be browsed.
