### ISSUE TITLE
Cannot Create New Subject in Schema Registry for release 0.10.0

### ISSUE THREAD

**Issue by akshayzendesk** [tchiotludo/kafkahq#166]
The release `0.10.0` does not allow creating new subject. The `Subject` , `Compatibility Level` & `Schema` are greyed out and we cannot add/edit any information for new schema. Following configuration is being used. As you can see, we have disabled the security and not limiting any user permissions.

```  
    micronaut:
      security:
        enabled: false

    kafkahq:
      server:
        access-log: # Access log configuration (optional)
          enabled: true # true by default
          name: org.kafkahq.log.access # Logger name
          format: "[Date: {}] [Duration: {} ms] [Url: {} {} {}] [Status: {}] [Ip: {}] [Length: {}] [Port: {}]" # Logger format

      # default kafka properties for each clients, available for admin / producer / consumer (optional)
      clients-defaults:
        consumer:
          properties:
            isolation.level: read_committed

      # list of kafka cluster available for kafkahq
      connections:
        my-cluster-sasl:
          properties:
            bootstrap.servers: "kafka:9092"
            security.protocol: SASL_PLAINTEXT
            sasl.mechanism: PLAIN
            sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="xxxxx";
          schema-registry:
            url: "http://schemaregistry:8081" # schema registry url (optional)

      pagination:
        page-size: 25 # number of elements per page (default : 25)
        threads: 16 # Number of parallel threads to resolve page

      # Topic list display options (optional)
      topic:
        retention: 172800000 # default retention period when creating topic
        partition: 1 #  default number of partition when creating topic
        replication: 3 # default number of replicas when creating topic
        default-view: HIDE_INTERNAL # default list view (ALL, HIDE_INTERNAL, HIDE_INTERNAL_STREAM, HIDE_STREAM)
        internal-regexps: # list of regexp to be considered as internal (internal topic can't be deleted or updated)
          - "^_.*$"
          - "^.*_schemas$"
          - "^.*connect-config$"
          - "^.*connect-offsets$1"
          - "^.*connect-status$"
        stream-regexps: # list of regexp to be considered as internal stream topic
          - "^.*-changelog$"
          - "^.*-repartition$"
          - "^.*-rekey$"
        skip-consumer-groups: true # Skip loading consumer group information when showing topics

      # Topic display data options (optional)
      topic-data:
        sort: OLDEST # default sort order (OLDEST, NEWEST) (default: OLDEST)
        size: 50 # max record per page (default: 50)
        poll-timeout: 1000 # The time, in milliseconds, spent waiting in poll if data is not available in the buffer.
```
