### ISSUE TITLE
Want to change default port from 8080 to any customize port

### ISSUE THREAD

**Issue by sunilmchaudhari** [tchiotludo/kafkahq#175]
Hi,
Since most of the components I am using has Java already been use. If I am running kafkaHQ on same  VM, it wont allow me to start saying 8080 is alredy in use.
Can I change the default port to some favourite port number?
How to do that?

regards,
Sunil.

**Comment by tchiotludo** [comment]
Hi, 

You can change all the http server configuration with config like that : https://docs.micronaut.io/latest/guide/index.html#runningSpecificPort

**Comment by amirensit** [comment]
For the given docker-compose example file, how can I change the port ?
https://raw.githubusercontent.com/tchiotludo/akhq/master/docker-compose.yml
It does not work for me

**Comment by amirensit** [comment]
I solved the problem this way:
```
  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        micronaut:
          server:
            port: 9080
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
```
