### ISSUE TITLE
Question : How to disable complete anonymous access 

### ISSUE THREAD

**Issue by rahulraina7** [tchiotludo/kafkahq#177]
According to readme and also what I see in my deployment 
By default, security & roles is enabled by default but anonymous user have full access

How do I always force login?

This is what my security configuration looks like, but this doesn't seem to be respected
I expect to only see nodes tab without login, but I see all the tabs.

```
security:
    default-roles: # Roles available for all the user even unlogged user
      - node/read
    # Basic auth configuration
    basic-auth:
      admin: # Username
        password: shapassword # Password in sha256
        roles: # Role for current users
          - topic/read
          - topic/insert
          - topic/delete
          - topic/config/update
          - node/read
          - node/config/update
          - topic/data/read
          - topic/data/insert
          - topic/data/delete
          - group/read
          - group/delete
          - group/offsets/update
          - registry/read
          - registry/insert
          - registry/update
          - registry/delete
          - registry/version/delete
          - connect/read
          - connect/insert
          - connect/update
          - connect/delete
          - connect/state/update

```
