### ISSUE TITLE
LDAP authentication doesn't work when group contains an underscore

### ISSUE THREAD

**Issue by legege** [tchiotludo/kafkahq#178]
Hi,

We've had trouble setting up LDAP authentication because our LDAP group contains an underscore. The underscore that is part of the group apparently gets interpreted by Micronaut configuration parser.

We've found a workaround: set the name property under the group definition.

```yaml
  security:
    ldap:
      group:
        ldap1:
          name: Enterprise_DevTeam
          groups:
            - read-write
        ldap2:
          name: Enterprise_Admin
          groups:
            - admin
            - read-write
```

It could be a good idea to document it and maybe standardize on this format.

**Comment by tchiotludo** [comment]
Hi, 

Have you just try to quote the name ? 
Seems to be weird that micronaut will convert a quoted string ?

**Comment by legege** [comment]
We've just tried and quoting the name doesn't work.

**Comment by tchiotludo** [comment]
ha ok !!! Just understand !! 

Your previous configuration was : 

```yaml 
  security:
    ldap:
      group:
        Enterprise_DevTeam:
          groups:
            - read-write
        Enterprise_Admin:
          groups:
            - admin
            - read-write
```

right ? 
If it the case, it's normal behaviour of micronaut !! 
And you have right, will add some documentation !
