### ISSUE TITLE
How to completely disable unauthenticated users

### ISSUE THREAD

**Issue by JakePDaniel** [tchiotludo/kafkahq#189]
I am currently trying to completely disable unauthenticated access to the site. 

This is my current configuration 

    security:
      default-group:
        - topic-reader
      groups:
        topic-reader: # Group name
          roles:  # roles for the group
            - topic/read
          attributes:
            # Regexp to filter topic available for group
            topics-filter-regexp: "test\\.reader.*"
        topic-writer:
          roles:
            - topic/read
            - topic/insert
            - topic/delete
            - topic/config/update
          topics-filter-regexp: "*"
      ldap:
        group:
          sdp-devops-admins:
            groups:
              - topic-reader
              - topic-writer

When first hitting the site I can see everything and can do any actions. When I log in with LDAP under the sdp-devops-admins group it successfully limits me to just my topic role.

I am using the default group to test limiting the access but would need to completely disable viewing the site for unauthenticated users. What do I need to add to the config to accomplish this?

**Comment by tchiotludo** [comment]
Not really sure without some test : 

maybe with : 
```yaml
security:
  default-group:
    - unauthenticated
  groups:
    unauthenticated: # Group name
      roles:  []
      attributes:
        # Regexp to filter topic available for group
        topics-filter-regexp: "test\\.reader.*"
    topic-writer:
      roles:
        - topic/read
        - topic/insert
        - topic/delete
        - topic/config/update
      topics-filter-regexp: "*"
  ldap:
    group:
      sdp-devops-admins:
        groups:
          - topic-reader
          - topic-writer

```
