### ISSUE TITLE
LDAP Configuration for KafkaHQ

### ISSUE THREAD

**Issue by vthorwat** [tchiotludo/kafkahq#197]
Hello ,

We are  planning to implement LDAP Authentication to Kafka Hq.

We are trying with below configurations but no luck with it. 

**Application.yml**
============================================
micronaut:
security:
ldap:
default:
enabled: true
context:
server: 'ldaps://adldap.abc.xyz.com:3269'
managerDn: 'CN=BIND_USER,OU=SERVICE ACCT,DC=abc,DC=xyz,DC=com'
managerPassword: 'D$ve&9IL'
search:
base: "DC=xyz,DC=com"
groups:
enabled: true
base: "DC=xyz,DC=com"
server:
port: 7070

kafkahq:
connections:
jbdl-dev:
properties:
bootstrap.servers: "BROKER:6667,BROKER:6667,BROKER:6667"
security.protocol: SASL_PLAINTEXT
authorizer.class.name: kafka.security.auth.SimpleAclAuthorizer
sasl.kerberos.service.name: kafka
sasl.jaas.config: com.sun.security.auth.module.Krb5LoginModule required useTicketCache=true useKeyTab=true keyTab="/etc/security/keytabs/kafka.service.keytab" principal="kafka/HOSTNAME@REALM.COM";

security:
default-groups:
- admin

groups:
admin:
roles:
- topic/read
- topic/insert
- topic/delete
- topic/config/update
- node/read
- node/config/update
- topic/data/read
- topic/data/insert
- topic/data/delete
- group/read
- group/delete
- group/offsets/update
- registry/read
- registry/insert
- registry/update
- registry/delete
- registry/version/delete
- acls/read
- connect/read
- connect/insert
- connect/update
- connect/delete
- connect/state/update

topic-reader:
roles:
- topic/read

endpoints:
env:
enabled: true
sensitive: false

======================================================
If anyone has implemented LDAP Authentication to KafkaHq their help is appreciated.

Thanks in advance.

**Comment by tchiotludo** [comment]
If you want to have help, please format your yaml to be readable ... 
Nobody can help you without format. 

I don't see any mapping between ldap group and kafkahq group in your yaml : 

```yaml 
kafkahq:
  security:
    ldap:
      group:
        mathematicians: # LDAP Group 
          groups:
            - topic-reader # Kafka HQ groups 
```

You can also debug ldap with this curl : 
```bash
curl -i -X POST -H "Content-Type: application/json" \
       -d '{ "configuredLevel": "TRACE" }' \
       http://localhost:8080/loggers/io.micronaut.configuration.security
```

**Comment by vthorwat** [comment]
Hi ,

After Mapping of my Admin LDAP group to admin group in KAfkaHq still I am not able to login to the page .

**ERROR LOG :**

![login_error_kafkahq](https://user-images.githubusercontent.com/14247410/73048187-43b65880-3e9e-11ea-9e9a-271ff219ca76.PNG)
 


**Please find the Group mapping in app.yml:** 

security:
default-groups:
- admin

groups:
admin:
roles:
- topic/read
- topic/insert
- topic/delete
- topic/config/update
- node/read
- node/config/update
- topic/data/read
- topic/data/insert
- topic/data/delete
- group/read
- group/delete
- group/offsets/update
- registry/read
- registry/insert
- registry/update
- registry/delete
- registry/version/delete
- acls/read
- connect/read
- connect/insert
- connect/update
- connect/delete
- connect/state/update

topic-reader:
roles:
- topic/read

ldap:
group:
GROUP--TOOLS--AMBARIMGMT:
groups:
- admin


=================================================


**LDAP CONFIG**

micronaut:
security:
ldap:
default:
enabled: true
context:
server: 'ldaps://adldap.xyz.abc.com:3269'
managerDn: 'CN=DEV_SVC_JPJ,OU=SERVICE ACCT,DC=xyz,DC=abc,DC=com'
managerPassword: 'D$ve&9IL'
search:
base: "DC=abc,DC=com"
groups:
enabled: true
base: "OU=BDL_DEV,OU=GROUPS,OU=IT,OU=MEMBER SERVERS,DC=xyz,DC=abc,DC=com"


===============================================


One more thing when i try to open Login page for KafkaHq it is showing us UNAUTHORIZED in URL DESCRIPTION as below but it still shows the login page.

![Login_Page_issue](https://user-images.githubusercontent.com/14247410/73047881-4c5a5f00-3e9d-11ea-9c19-c9fae6ba5e8d.PNG)

**Comment by vthorwat** [comment]
One question I am having regarding LDAP mapping .

We have to configure it wihin "kafkahq:" or in "micronaut:"

I am currently configuring it in the "kafkahq:".

**Comment by tchiotludo** [comment]
To properly format code, use https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code please, still unreadable ! 

Mapping must be done in `kafkahq:` , `micronaut:` configuration is necessary only for ldap server configuration.

For the the mapping to work with special characters, just must use the trick here https://github.com/tchiotludo/kafkahq/issues/178.
so must be a configuration (part) like : 
```yaml 
security:
  ldap:
    group:
      ambarimgmt: # not really important id that will be override by name below
        name: GROUP--TOOLS--AMBARIMGMT
        groups:
         - admin
```

**Comment by vthorwat** [comment]
Thanks for reply..

I tried with the given changes but still USER NOT FOUND error is getting while login to KafkaHq

Please find the application.yml :

```
micronaut:
  security:
     ldap:
       default:
         enabled: true
         context:
              server: 'ldaps://adldap.xyz.abc.com:3269'
              managerDn: 'CN=BIND_USER,OU=SERVICE ACCT,DC=xyz,DC=abc,DC=com'
              managerPassword: 'BIND_PASSWORD'
         search:
              base: "DC=abc,DC=com"
         groups:
              enabled: true
              base: "OU=BDL_DEV,OU=GROUPS,OU=IT,OU=MEMBER SERVERS,DC=xyz,DC=abc,DC=com"

  server:
    port: 7070
kafkahq:
 connections:
    jbdl-dev:
      properties:
        bootstrap.servers: "BROKER:6667,BROKER:6667,BROKER:6667"
        security.protocol: SASL_PLAINTEXT
        authorizer.class.name: kafka.security.auth.SimpleAclAuthorizer
        sasl.kerberos.service.name: kafka
        sasl.jaas.config: com.sun.security.auth.module.Krb5LoginModule required useTicketCache=true useKeyTab=true keyTab="/etc/security/keytabs/kafka.service.keytab" principal="kafka/HOSTNAME@REALM.COM";

 security:
   default-groups:
        -
 groups:
   admin:
    roles:
      - topic/read
      - topic/insert
      - topic/delete
      - topic/config/update
      - node/read
      - node/config/update
      - topic/data/read
      - topic/data/insert
      - topic/data/delete
      - group/read
      - group/delete
      - group/offsets/update
      - registry/read
      - registry/insert
      - registry/update
      - registry/delete
      - registry/version/delete
      - acls/read
      - connect/read
      - connect/insert
      - connect/update
      - connect/delete
      - connect/state/update
    attributes:
     topics-filter-regexp: "test.*"

   topic-reader:
     roles:
       - topic/read
     attributes:
       topics-filter-regexp: "test\\.reader.*"
 ldap:
   group:
     ambari:
       name: GROUP--TOOLS--AMBARIMGMT
       groups:
         - admin
         - topic-reader
endpoints:
    env:
    enabled: true
    sensitive: false
```

Please let me know if any other changes required.

**Comment by tchiotludo** [comment]
Each ldap is a different kind of monster ... 
Really hard to debug remotely.

All the Ldap configuration is micronaut based here : https://micronaut-projects.github.io/micronaut-security/latest/guide/#ldap

Most of the configuration is simple mapping from java. 
Don't you have a java application connected to ldap in your org to help you ?

**Comment by vthorwat** [comment]
Yes we are validating the same. But looks all ok.

Still figuring why this is occuring.

As from the configurations we are able to understand that configurations for connecting to ldap are connect only problem is We are not able to search the user in AD.

We are filtering the groups in config like this :


```
micronaut:
  security:
      ldap:
        default:
          enabled: true
          context:
               server: 'ldaps://adldap.xyz.abc.com:3269'
               managerDn: 'cn=BIND_USER,ou=SERVICE ACCT,dc=xyz,dc=abc,dc=com'
               managerPassword: 'PASSWORD'
          search:
               enabled: true
               base: "dc=ril,dc=com"
          groups:
               enabled: true
               base: "ou=BDL_DEV,ou=GROUPS,ou=IT,ou=MEMBER SERVERS,dc=xyz,dc=abc,dc=com"
               filter: "cn=GALL--DEVBDL--*"
               attribute: "cn"

```

Please can you just check whether is correct or not?
