### ISSUE TITLE
Docker image version 0.12.0 doesn't expose Connect workers

### ISSUE THREAD

**Issue by phills** [tchiotludo/kafkahq#208]
"Connect" does not appear at the bottom of the left menu.  It worked in 0.10.0 and 0.11.0
Thanks

**Comment by tchiotludo** [comment]
Last version handle multiple connect server , Now the configuration expect an array  : https://github.com/tchiotludo/kafkahq/blob/612cd18b4c7529b84a8d0937dd85b6b5fc1bfa97/application.example.yml#L45
```yaml 
      connect:
        - name: connect-1
          url: "http://connect:8083"
```
