### ISSUE TITLE
Using ldaps on port 636 with certificate ?

### ISSUE THREAD

**Issue by apellegr06** [tchiotludo/kafkahq#226]
Hello,

I try to use ldap in a secured way with ldaps and port 636 but it doesn't work for now.

I have found some documentation about micronaut (http://www.jeffschwartz.net/micronaut/guide/index.html) but I don't know where to put the section ssl in the yml file :

```
ssl:
  enabled: true
  keyStore:
    path: file:toto.pem
    password:
    type: PEM

```
And also I'm not sure that the type is PEM and the password could be empty.

Coudl you help me ?
