### ISSUE TITLE
Docs : Permissions not enforced / Groups & Roles

### ISSUE THREAD

**Issue by ebrard** [tchiotludo/kafkahq#239]
It seems that permissions are not enforced in 0.12.0, for example if I set the application up with:
```
kafkahq:
  security:
    default-roles:
      - topic/read
      - node/read
      - topic/data/read
      - group/read
      - registry/read
      - connect/read
```

I can still delete topics. Adding a default group with the same rights did not solve it.

**Comment by tchiotludo** [comment]
Hi, 

look at this one : https://github.com/tchiotludo/kafkahq/issues/224

There is a fix on `dev` branch waiting to be release

**Comment by ebrard** [comment]
Ah thanks, I didn't see this one before. When do you think you will make a new version release or push the fix into 0.12.0?

**Comment by tchiotludo** [comment]
Soon I think, I was hoping to have a confirmation that the fix works that was not coming :p

**Comment by ebrard** [comment]
Is it already part of the dev docker image?

**Comment by tchiotludo** [comment]
yes the dev branch is auto build

**Comment by ebrard** [comment]
ah then I'll check today in our infra and let you know

**Comment by ebrard** [comment]
Now running the snapshot one, is `default-roles:` still supposed to be enforced or is it deprecated in favour of default-group?

**Comment by tchiotludo** [comment]
`default-roles:` must be removed from doc and not used anymore. 
`default-group` is the right one now

**Comment by ebrard** [comment]
unlogged user seems to get the right rights now, but logged in user don't get the admin role as defined in this conf:
```
  security:
    default-group: ouruser # Default groups for all the user even unlogged user
    # Groups definition
    groups:
      ouruser: # Group name
        roles:  # roles for the group
          - topic/read
          - topic/insert
          - node/read
          - topic/data/read
          - group/read
          - registry/read
          - registry/insert
          - registry/update
          - connect/read
          - group/offsets/update
          - acls/read
        attributes:
          # Regexp to filter topic available for group
          topics-filter-regexp: "db-stream.*"
    basic-auth:
      admin:
        password: notshown
        roles:
          - admin
```
Actually when I'm logged as admin, all items of the right side list disappear. Do I need to redefine the admin role?

**Comment by tchiotludo** [comment]
Look at these : 
https://github.com/tchiotludo/kafkahq/blob/2e2cde3b85114529484b4af92ccade7a93d39dfa/application.example.yml#L157-L162

must be : 
```yaml
    basic-auth:
      admin:
        password: notshown
        groups:
          - admin
```
