### ISSUE TITLE
Can't set host/port since upgrading to micronaut

### ISSUE THREAD

**Issue by johnseekins** [tchiotludo/kafkahq#33]
If I want this tool to listen on say, `0.0.0.0` or a different port, how do I actually set that? The docs don't seem to mention anything. And currently, I'm stuck only listening on localhost, which makes it hard to use.

**Comment by tchiotludo** [comment]
If think you can use this parameters : 
https://docs.micronaut.io/1.1.0.M1/guide/configurationreference.html#io.micronaut.http.server.HttpServerConfiguration

especially : `micronaut.server.port` and `micronaut.server.host` to change this configuration ? 

What seems weird is by default micronaut listen on 0.0.0.0.

**Comment by johnseekins** [comment]
```root@dlt-logging-kafka-1:/opt/kafkahq# cat /opt/kafkahq/kafkahq.yml 
kafkahq:
  micronaut:
    server:
      port: 9090
      host: "0.0.0.0"
  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed
  connections:
    logging-kafka:
      properties:
        bootstrap.servers: "10.40.250.5:9092,10.40.250.6:9092,10.40.250.7:9092"
root@dlt-logging-kafka-1:/opt/kafkahq# MICRONAUT_CONFIG_FILES=/opt/kafkahq/kafkahq.yml java -jar /opt/kafkahq/kafkahq.jar prod
2019-02-25 11:57:49,353 INFO  main       i.m.runtime.Micronaut      Startup completed in 2588ms. Server Running: http://localhost:8080
```

Doesn't seem that way.

**Comment by tchiotludo** [comment]
It's micronaut config so no need for the kafkahq prefix : 
Your config must look like this : 
```yml
micronaut:
  server:
    port: 9090
    host: "0.0.0.0"
kafkahq:
  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed
  connections:
    logging-kafka:
      properties:
        bootstrap.servers: "10.40.250.5:9092,10.40.250.6:9092,10.40.250.7:9092"
```
