### ISSUE TITLE
Quick preview doesn't work - com.typesafe.config.ConfigException$Parse

### ISSUE THREAD

**Issue by rmoff** [tchiotludo/kafkahq#51]
Trying to run the quickstart

1. Cloned repo
2. Checked out master
3. `docker-compose up -d`
4. Error in `kafkahq` container:  

        com.typesafe.config.ConfigException$Parse: /app/application.conf: 1: Expecting end of input or a comma, got ':' (if you intended ':' to be part of a key or string value, try enclosing the key or value in double quotes)

Looking at the container: 

Env has been set correctly: 

```
/app # env
JAVA_ALPINE_VERSION=8.191.12-r0
HOSTNAME=c5e34470976b
SHLVL=1
HOME=/root
KAFKAHQ_CONFIGURATION=kafkahq:
  connections:
    docker-kafka-server:
      properties:
        bootstrap.servers: "kafka:9092"
      schema-registry: "http://schema-registry:8085"
      connect: "http://connect:8083"

JAVA_VERSION=8u191
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
LANG=C.UTF-8
JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk/jre
PWD=/app
```

But config file has no line breaks: 

```
/app # cat application.conf
kafkahq: connections: docker-kafka-server: properties: bootstrap.servers: "kafka:9092" schema-registry: "http://schema-registry:8085" connect: "http://connect:8083"
```

Strangely, if I run [this](https://github.com/tchiotludo/kafkahq/blob/77c87e3078c8fdf77c2fc4e5fb37a3017b8b3486/docker/usr/local/bin/docker-entrypoint.sh#L6) manually the file is written correctly: 

```
/app # echo "${KAFKAHQ_CONFIGURATION}" > /tmp/foo
/app # cat /tmp/foo
kafkahq:
  connections:
    docker-kafka-server:
      properties:
        bootstrap.servers: "kafka:9092"
      schema-registry: "http://schema-registry:8085"
      connect: "http://connect:8083"
```
