### ISSUE TITLE
No schema registry view after config set up

### ISSUE THREAD

**Issue by przemyslawsikora** [tchiotludo/kafkahq#53]
There is no Schema Registry view on the UI, even the valid configurartion of the Kafka, Schema Registry and KafkaHQ have been prepared.

Configuration of the KafkaHQ:
```YAML
kafkahq:
  server:
    base-path: ""
  connections:
    cultural-cluster:
      properties:
        bootstrap.servers: "kafka:9092"
      schema-registry:
        url: "http://schema-registry:8085"
```

Kafka, Schema Registry and KafkaHQ are running on Docker
Installation prepared in Ansible:
```YAML
- name: Create Docker network
  docker_network:
    name: "docker_network"

- name: Pull Zookeeper image
  docker_image:
    name: zookeeper
    tag: 3.5

- name: Create Zookeeper data volume
  docker_volume:
    name: zookeeper_data

- name: Create Zookeeper logs volume
  docker_volume:
    name: zookeeper_logs

- name: Create Zookeeper container
  docker_container:
    name: zookeeper
    image: zookeeper:3.5
    restart_policy: always
    network_mode: "docker_network"
    networks:
      - name: "docker_network"
        aliases:
          - zookeeper
    hostname: zookeeper
    volumes:
      - zookeeper_data:/data
      - zookeeper_logs:/datalog
    env:
      ZOO_MY_ID: "1"
      ZOO_AUTOPURGE_PURGEINTERVAL: "3"

- name: Pull Kafka image
  docker_image:
    name: confluentinc/cp-kafka
    tag: 5.2.1

- name: Create Kafka data volume
  docker_volume:
    name: kafka_data

- name: Create Kafka container
  docker_container:
    name: kafka
    image: confluentinc/cp-kafka:5.2.1
    restart_policy: always
    network_mode: "docker_network"
    networks:
      - name: "docker_network"
        aliases:
          - kafka
    hostname: kafka
    published_ports:
      - 127.0.0.1:9093:9093
    volumes:
      - kafka_data:/var/lib/kafka/data
    env:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_LOG_RETENTION_HOURS: "-1"

- name: Pull Schema Registry image
  docker_image:
    name: confluentinc/cp-schema-registry
    tag: 5.2.1

- name: Create Schema Registry container
  docker_container:
    name: schema-registry
    image: confluentinc/cp-schema-registry:5.2.1
    restart_policy: always
    network_mode: "docker_network"
    networks:
      - name: "docker_network"
        aliases:
          - schemaregistry
    hostname: schemaregistry
    env:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:9092"
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8085"
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
    published_ports:
      - 127.0.0.1:8085:8085

- name: Pull KafkaHQ image
  docker_image:
    name: tchiotludo/kafkahq
    tag: 0.6.1

- name: Create KafkaHQ container
  docker_container:
    name: kafkahq
    image: tchiotludo/kafkahq:0.6.1
    restart_policy: always
    recreate: yes
    network_mode: "docker_network"
    networks:
      - name: "docker_network"
        aliases:
          - kafkahq
    hostname: kafkahq
    volumes:
      - "{{ playbook_dir }}/roles/{{role_name}}/files/kafkahq.yml:/app/application.yml"
    published_ports:
      - 127.0.0.1:8080:8080

- name: Create Kafka topic 'test_topic'
  docker_container:
    name: kafka-topic-cultural-data
    image: confluentinc/cp-kafka:5.2.1
    auto_remove: yes
    network_mode: "docker_network"
    networks:
      - name: "docker_network"
    command:
      - kafka-topics
      - --create
      - --topic test_topic
      - --partitions 1
      - --replication-factor 1
      - --if-not-exists
      - --zookeeper zookeeper:2181
```

Everything working very well: producers, consumers, schema registry with Avro (serializing, deserializing), KafkaHQ too, except the view of schemas. Any additional configuration required or it's bug?
Fetching http://localhost:8085/subjects brings valid schema list.
Version of KafkaHQ used in the example is 0.6.1 (the newest one)
