### ISSUE TITLE
Cannot see connect tab.

### ISSUE THREAD

**Issue by rahulraina7** [tchiotludo/kafkahq#54]
I am using the latest jar file.

**Comment by tchiotludo** [comment]
I think It's because the main branch is based on develop.

You may are using the configuration based on develop branch with image based on master branch.

The next release will change the configuration, look at this, for your current version :
https://github.com/tchiotludo/kafkahq/blob/master/application.example.yml

I think It's not clear the first displayed branch is develop.

**Comment by rahulraina7** [comment]
> I think It's because the main branch is based on develop.
> 
> You may are using the configuration based on develop branch with image based on master branch.
> 
> The next release will change the configuration, look at this, for your current version :
> https://github.com/tchiotludo/kafkahq/blob/master/application.example.yml
> 
> I think It's not clear the first displayed branch is develop.

How can I use the develop branch.

This is how i run it currently.

`java -Dmicronaut.config.files=kafkahq_app.yml -jar kafkahq.jar prod"

I did try replacing prod with `develop` or `dev`

**Comment by tchiotludo** [comment]
You can't for now with java jar. 
I currently only publish a [docker tag  `dev`](https://hub.docker.com/r/tchiotludo/kafkahq/tags) not the jar.

In a mean time, you can follow the doc here : https://github.com/tchiotludo/kafkahq/tree/master

You have to just changed your `configuration.yml` (current release) to  
```yaml
    my-cluster-plain-text: # url friendly name for the cluster
      properties: # standard kafka properties (optional)
        bootstrap.servers: "kafka:9092"
      schema-registry: "http://schema-registry:8085" # schema registry url (optional)
      connect: "http://connect:8083" # connect url (optional)
``` 
instead of (next release)
```yaml
    my-cluster-plain-text: # url friendly name for the cluster
      properties: # standard kafka properties (optional)
        bootstrap.servers: "kafka:9092"
      schema-registry:
        url: "http://schema-registry:8085" # schema registry url (optional)
        basic-auth: # Basic Auth user / pass
          username: basic-auth-user
          password: basic-auth-pass
      connect:
        url: "http://connect:8083" # connect url (optional)
        basic-auth: # Basic Auth user / pass (optional)
          username: basic-auth-user
          password: basic-auth-pass
        ssl: # ssl store configuration (optional)
          trust-store: /app/truststore.jks
          trust-store-password: trust-store-password
          key-store: /app/truststore.jks
          key-store-password: key-store-password
```

Especially : 
```yaml
      connect: "http://connect:8083"
```

instead of


```yaml
      connect:
        url: "http://connect:8083"```
```

**Comment by rahulraina7** [comment]
I did try both of these. Especially after reading https://github.com/tchiotludo/kafkahq/issues/53
However, I can't still view connect. I can view Schema Registry though

**Comment by tchiotludo** [comment]
Ok, So it may be [acl](https://github.com/tchiotludo/kafkahq/blob/dev/application.example.yml#L86).

Can you send the `application.yml` please ?

**Comment by rahulraina7** [comment]
Ok I did never added the acls. But I just tried even that, still doesn't show up.

This is how it looks currently.

```
micronaut:
  server:
    host: "0.0.0.0"
    port: 9009
kafkahq:
  server:
    # if behind a reverse proxy, path to kafkahq with trailing slash
    #base-path: "/kafkahq"

  # default kafka properties for each clients, available for admin / producer / consumer (optionnal)
  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed

  # list of kafka cluster available for kafkahq
  connections:
    # url friendly name for the cluster
    prod:
      # standard kafka properties (optionnal)
      properties:
        bootstrap.servers: ""
        security.protocol: "SSL"
        ssl.truststore.location: ""
        ssl.truststore.password: ""
        ssl.keystore.location: ""
        ssl.keystore.password: ""
        ssl.key.password: ""
        ssl.endpoint.identification.algorithm: ""
      # schema registry url (optionnal)
      schema-registry: ""
      connect:
        url: ""

  security:
    default-roles: # Roles available for all the user even unlogged user
      - topic/read
      - node/read
      - group/read
      - registry/read
      - connect/read

    # Basic auth configuration
    basic-auth:
      admin: # Username
        password: "***"
        roles: # Role for current users
          - topic/read
          - topic/insert
          - topic/delete
          - topic/config/update
          - node/read
          - node/config/update
          - topic/data/read
          - topic/data/insert
          - topic/data/delete
          - group/read
          - group/delete
          - group/offsets/update
          - registry/read
          - registry/insert
          - registry/update
          - registry/delete
          - registry/version/delete
          - connect/read
          - connect/insert
          - connect/update
          - connect/delete
          - connect/state/update

```

**Comment by tchiotludo** [comment]
Ok got it, just changed : 

```yaml
      schema-registry: ""
      connect:
        url: ""
```
to 
```yaml
      schema-registry: ""
      connect: ""
```
