### ISSUE TITLE
Basic Auth user configuration not working

### ISSUE THREAD

**Issue by ebacklund** [tchiotludo/kafkahq#57]
When configuring basic-auth for a user per the readme instructions:
```
  # Auth & Roles (optional)
  security:
    default-roles: # Roles available for all the user even unlogged user READONLY until locked down
    - topic/read
    - node/read
    - topic/data/read
    - group/read
    - registry/read
    - connect/read
    basic-auth:
      username: admin
        password: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        roles:
        - topic/insert
        - topic/delete
        - topic/config/update
        - node/config/update
        - topic/data/insert
        - topic/data/delete
        - group/delete
        - group/offsets/update
        - registry/update
        - registry/delete
        - registry/version/delete
```

The application fails to start with the following error:
```
org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'reader', line 48, column 17:
            password: 8c6976e5b5410415bde908bd4dee15 ...
```

If I update the yaml configuration to NOT indent the password and roles, application will startup successfully but I can not log into the application.
```
    basic-auth:
      username: admin
      password: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      roles:
      - topic/insert
      - topic/delete
      - topic/config/update
      - node/config/update
      - topic/data/insert
      - topic/data/delete
      - group/delete
      - group/offsets/update
      - registry/update
      - registry/delete
      - registry/version/delete
```

This is what is outputted to the application log when attempting to login:
```
2019-05-09 19:04:57,119 INFO  pGroup-1-2 org.kafkahq.log.access     [Date: 2019-05-09T19:04:57.088348Z] [Duration: 28 ms] [Url: POST /login HTTP/1.1] [Status: 303] [Ip: 172.27.85.121][Length: 0] [Port: 8080]
2019-05-09 19:04:57,154 INFO  pGroup-1-3 org.kafkahq.log.access     [Date: 2019-05-09T19:04:57.134093Z] [Duration: 19 ms] [Url: GET /login/failed HTTP/1.1] [Status: 200] [Ip: 172.27.85.121] [Length: 679] [Port: 8080]
```

**Comment by tchiotludo** [comment]
your yaml is invalid, here is the good one : 

```yaml
  # Auth & Roles (optional)
  security:
    default-roles: # Roles available for all the user even unlogged user READONLY until locked down
    - topic/read
    - node/read
    - topic/data/read
    - group/read
    - registry/read
    - connect/read
    basic-auth:
      admin: 
        password: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        roles:
        - topic/insert
        - topic/delete
        - topic/config/update
        - node/config/update
        - topic/data/insert
        - topic/data/delete
        - group/delete
        - group/offsets/update
        - registry/update
        - registry/delete
        - registry/version/delete
```
especially this part : 

```yaml 
    basic-auth:
      username: admin
        password: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
```
username must be replace by the current login and not added after `:` that is an invalid yaml
