### ISSUE TITLE
When exploring data in a topic, sorting of upper right green arrow brings authentication screen

### ISSUE THREAD

**Issue by ftardif** [tchiotludo/kafkahq#62]
I believe the configuration should already grant all roles, so why do I get the auth screen (I don't even know what user/pass) to provide:

[ftardif@fonse-db1 ~]$ cat /opt/kafkahq/application.yml
---
kafkahq:
  server:
    base-path: "/kafka/kafkahq"
  connections:
    kafka-vic:
      properties:
        bootstrap.servers: geo-kafka-broker.query.consul:9092
      schema-registry:
        url: http://geo-kafka-schema-registry.query.consul:8081

  security:
    default-roles:
      - topic/read
      - node/read
      - topic/data/read
      - group/read
      - registry/read
      - connect/read
      - topic/delete
      - topic/config/update
      - node/config/update
      - topic/data/insert
      - topic/data/delete
      - group/delete
      - group/offsets/update
      - registry/insert
      - registry/update
      - registry/delete
      - registry/version/delete
      - connect/
      - connect/insert
      - connect/update
      - connect/delete
      - connect/state/update

**Comment by tchiotludo** [comment]
On micronaut (java base framework), a non existing route will lead to unauthorized url.
The url was wrong on this pagination when using a `base-path`.

Fix :+1: 
Thanks for the report :+1: 

BTW,  you can use a simple configuration files like that :  
```yaml
kafkahq:
    server:
        base-path: "/kafka/kafkahq"
    connections:
        kafka-vic:
            properties:
                bootstrap.servers: geo-kafka-broker.query.consul:9092
            schema-registry:
                url: http://geo-kafka-schema-registry.query.consul:8081
```

Default roles is already defined on base configuration.
