### ISSUE TITLE
login does not stick between controllers

### ISSUE THREAD

**Issue by ftardif** [tchiotludo/kafkahq#65]
If I log in the app (let's say from the topic list page) and then I go in the consumergroup page, I see the login button on the lower left does not show me as logged in anymore. Then if I click on a given consumer group and I try to update the offset (the update button is available), it brings me back on the login page. If I log, I am back at the home of the app and if I navigate back to my consumer group, I am still not recognized as logged in.

my config is the following:
---
```
kafkahq:
  server:
    base-path: "/kafka/kafkahq"
  connections:
    kafka-vic:
      properties:
        bootstrap.servers: geo-kafka-broker.query.consul:9092
      schema-registry:
        url: http://geo-kafka-schema-registry.query.consul:8081

  security:
    default-roles:
      - topic/read
      - node/read
      - topic/data/read
      - group/read
      - registry/read
      - connect/read
    basic-auth: # admin/admin
      admin:
        password: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        roles:
          - topic/insert
          - topic/delete
          - topic/config/update
          - node/config/update
          - topic/data/insert
          - topic/data/delete
          - group/delete
          - group/offsets/update
          - registry/insert
          - registry/update
          - registry/delete
          - registry/version/delete
          - connect/
          - connect/insert
          - connect/update
          - connect/delete
          - connect/state/update
```
