### ISSUE TITLE
help with cluster not found errors

### ISSUE THREAD

**Issue by larryzhu2018** [tchiotludo/kafkahq#68]
hi, Can you please help me troubleshoot the error I reported with this PR: https://github.com/tchiotludo/kafkahq/pull/67

Thanks,
--larry

**Comment by tchiotludo** [comment]
Quick look, and it seems that the app filename is wrong on your `docker-compose.yml`.

on : 
```yaml
services:
  kafkahq:
    # build:
    #   context: .
    image: tchiotludo/kafkahq
    volumes:
      - ./app.yaml:/app/application.yaml
    ports:
      - 8080:8080
    links:
      - helk-kafka
      - kafka-schema-registry
```

the `- ./app.yaml:/app/application.yaml` must be `- ./app.yaml:/app/application.yml`.  not `yaml`
Look at the based framework of kafkahq : https://docs.micronaut.io/snapshot/guide/index.html#config
> The convention is to search for a file called application.yml, application.properties, application.json or application.groovy.
