### ISSUE TITLE
login does not authorize some topic browsing functions

### ISSUE THREAD

**Issue by ftardif** [tchiotludo/kafkahq#69]
although I am logged in with all roles, when doing basic browsing (such as sorting, or clicking upper right green paging arrow), I am always redirected to the login page.

see video:
https://photos.app.goo.gl/ibSZnP93CcUUbijm7

**Comment by ftardif** [comment]
my config is:
```
[ftardif@fonse-db1 ~]$ cat /opt/kafkahq/application.yml
---
kafkahq:
  server:
    base-path: "/kafka/kafkahq"
  connections:
    kafka-vic:
      properties:
        bootstrap.servers: geo-kafka-broker.query.consul:9092
      schema-registry:
        url: http://geo-kafka-schema-registry.query.consul:8081

  security:
    default-roles:
      - topic/read
      - node/read
      - topic/data/read
      - group/read
      - registry/read
      - connect/read
    basic-auth:
      vtsoftware:
        password: d426bd23673efe2c1cbd537ea97fae573f5bce9f8a594f7586a0235e26dab87d
        roles:
          - topic/insert
          - topic/delete
          - topic/config/update
          - node/config/update
          - topic/data/insert
          - topic/data/delete
          - group/delete
          - group/offsets/update
          - registry/insert
          - registry/update
          - registry/delete
          - registry/version/delete
          - connect/
          - connect/insert
          - connect/update
          - connect/delete
          - connect/state/update
```
