### ISSUE TITLE
Deployment on Kubernetes fails

### ISSUE THREAD

**Issue by weeco** [tchiotludo/kafkahq#90]
When I deploy and run Kafka HQ on Kubernetes it fails because of:

```
$ kubectl.exe  logs -f kafka-hq-786784cbb8-4668d
/usr/local/bin/docker-entrypoint.sh: 9: exec: ./kafkahq: not found
```

I believe this is due to missing permissions on the path and must be fixed in the docker image.

**Comment by tchiotludo** [comment]
As I know, deployment on kubernetes works well. 
The `kafkahq` command as also the right permission.

I think you have change the workdir on your k8s configuration (default `WORKDIR /app`) ? 
and in this case, you must change the command to be absolute (default `CMD ["./kafkahq"]`)
Just change command to `/app/kafkahq` and it must be working as I understand.

Tell me if it work

**Comment by weeco** [comment]
I can't confirm this has worked, nor did I ever had to change the docker entrypoint in my kubernetes manifests. I am running on Google's GKE. This should be fairly reproducible, here's the kubernetes manifest I apply:

https://gist.github.com/weeco/be9b631e10564475073886c0a4042cf5

**Comment by tchiotludo** [comment]
OK got it ! 
Already have the bug on my side. 

```yaml
          volumeMounts:
            - mountPath: /app
              name: config
              readOnly: true
```
You are mounting the `/app` in order to inject the configuration. 
And it remove all the binary from kafkahq leading to this error. 

I suggest you to use the `MICRONAUT_CONFIG_FILES` env var to change the configuration path like `/app/configurations/` and to mount this directory for configuration on your pods. 
or to use directly `KAFKAHQ_CONFIGURATION` env var with configuration, like you want.

**Comment by weeco** [comment]
Ah that makes sense, I didn't think about that. What I did to fix is to edit the volume mount so that it just adds the file into that folder:

```
          volumeMounts:
            - mountPath: /app/application.yml
              subPath: application.yml
              name: config
              readOnly: true
```

Now it has the application.yml and all the other files from the docker image in that folder. Thank you for your quick responses. Speaking of cloud environments, do you have a setting do print all log messages in JSON format?
