### ISSUE TITLE
Issue with configuration file: couldn't find any cluster

### ISSUE THREAD

**Issue by federicovagnoni** [tchiotludo/kafkahq#95]
I read about this problem in other closed issues, but I really cannot understand what I'm doing wrong!

```yaml
kafkahq:
  # list of kafka cluster available for kafkahq
  connections:
    test-1: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "localhost:9092"

  # Basic auth configuration
  basic-auth:
    user: # Username
      password: pass # Password in sha256
      roles: # Role for current users
        - topic/read
        - group/read
        - group/delete
```

I launch the container in this way, because kafka is running locally.

```
docker run -d \
    --network="host" \
    -e MICRONAUT_CONFIG_FILES=/app/micronaut.properties \
    -v /data/kafkahq/micronaut/application.properties:/app/micronaut.properties \
    -v /data/kafkahq/application.yml:/app/application.yml \
    tchiotludo/kafkahq
```
